# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Post.create(body: 'Bulbasaur Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ivysaur Lorem ipsum')
Post.create(body: 'Pokem ipsum dolor sit amet Shiftry Vigoroth Suicune Venonat Vullaby Beldum. Lavender Town')
Post.create(body: 'Swablu Ghost Charizard Cleffa Tropius Keldeo. Mewtwo Strikes Back Super Potion Magikarp used')
Post.create(body: 'Splash Wailmer Deoxys Giovanni Sableye. Glitch City Seadra bicycle Larvitar Rainbow Badge')
Post.create(body: 'Druddigon Skarmory. Charizard Munchlax Vibrava Salamence Volcano Badge Rampardos')
Post.create(body: 'Quis nostrud exercitation ullamco laboris nisi Potion Magmar Druddigon')
Post.create(body: 'Zephyr Badge Palpitoad Bubble Snivy Omanyte')
Post.create(body: 'Mantine Krookodile. Sinnoh Hidden Machine gotta catch \'em all Hydreigon Cacnea Raticate Flygon')
Post.create(body: 'Dragon Rage Staravia Running Shoes Masquerain Jolteon Pokemon Heroes Lugia.')
Post.create(body: 'Bulbasaur Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ivysaur Lorem ipsum')
Post.create(body: 'Pokem ipsum dolor sit amet Shiftry Vigoroth Suicune Venonat Vullaby Beldum. Lavender Town')
Post.create(body: 'Swablu Ghost Charizard Cleffa Tropius Keldeo. Mewtwo Strikes Back Super Potion Magikarp used')
Post.create(body: 'Splash Wailmer Deoxys Giovanni Sableye. Glitch City Seadra bicycle Larvitar Rainbow Badge')
Post.create(body: 'Druddigon Skarmory. Charizard Munchlax Vibrava Salamence Volcano Badge Rampardos')
Post.create(body: 'Quis nostrud exercitation ullamco laboris nisi Potion Magmar Druddigon')
Post.create(body: 'Zephyr Badge Palpitoad Bubble Snivy Omanyte')
Post.create(body: 'Mantine Krookodile. Sinnoh Hidden Machine gotta catch \'em all Hydreigon Cacnea Raticate Flygon')
Post.create(body: 'Dragon Rage Staravia Running Shoes Masquerain Jolteon Pokemon Heroes Lugia.')
Post.create(body: 'Bulbasaur Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ivysaur Lorem ipsum')
Post.create(body: 'Pokem ipsum dolor sit amet Shiftry Vigoroth Suicune Venonat Vullaby Beldum. Lavender Town')
Post.create(body: 'Swablu Ghost Charizard Cleffa Tropius Keldeo. Mewtwo Strikes Back Super Potion Magikarp used')
Post.create(body: 'Splash Wailmer Deoxys Giovanni Sableye. Glitch City Seadra bicycle Larvitar Rainbow Badge')
Post.create(body: 'Druddigon Skarmory. Charizard Munchlax Vibrava Salamence Volcano Badge Rampardos')
Post.create(body: 'Quis nostrud exercitation ullamco laboris nisi Potion Magmar Druddigon')
Post.create(body: 'Zephyr Badge Palpitoad Bubble Snivy Omanyte')
Post.create(body: 'Mantine Krookodile. Sinnoh Hidden Machine gotta catch \'em all Hydreigon Cacnea Raticate Flygon')
Post.create(body: 'Dragon Rage Staravia Running Shoes Masquerain Jolteon Pokemon Heroes Lugia.')
Post.create(body: 'Bulbasaur Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ivysaur Lorem ipsum')
Post.create(body: 'Pokem ipsum dolor sit amet Shiftry Vigoroth Suicune Venonat Vullaby Beldum. Lavender Town')
Post.create(body: 'Swablu Ghost Charizard Cleffa Tropius Keldeo. Mewtwo Strikes Back Super Potion Magikarp used')
Post.create(body: 'Splash Wailmer Deoxys Giovanni Sableye. Glitch City Seadra bicycle Larvitar Rainbow Badge')
Post.create(body: 'Druddigon Skarmory. Charizard Munchlax Vibrava Salamence Volcano Badge Rampardos')
Post.create(body: 'Quis nostrud exercitation ullamco laboris nisi Potion Magmar Druddigon')
Post.create(body: 'Zephyr Badge Palpitoad Bubble Snivy Omanyte')
Post.create(body: 'Mantine Krookodile. Sinnoh Hidden Machine gotta catch \'em all Hydreigon Cacnea Raticate Flygon')
Post.create(body: 'Dragon Rage Staravia Running Shoes Masquerain Jolteon Pokemon Heroes Lugia.')
Post.create(body: 'Bulbasaur Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ivysaur Lorem ipsum')
Post.create(body: 'Pokem ipsum dolor sit amet Shiftry Vigoroth Suicune Venonat Vullaby Beldum. Lavender Town')
Post.create(body: 'Swablu Ghost Charizard Cleffa Tropius Keldeo. Mewtwo Strikes Back Super Potion Magikarp used')
Post.create(body: 'Splash Wailmer Deoxys Giovanni Sableye. Glitch City Seadra bicycle Larvitar Rainbow Badge')
Post.create(body: 'Druddigon Skarmory. Charizard Munchlax Vibrava Salamence Volcano Badge Rampardos')
Post.create(body: 'Quis nostrud exercitation ullamco laboris nisi Potion Magmar Druddigon')
Post.create(body: 'Zephyr Badge Palpitoad Bubble Snivy Omanyte')
Post.create(body: 'Mantine Krookodile. Sinnoh Hidden Machine gotta catch \'em all Hydreigon Cacnea Raticate Flygon')
Post.create(body: 'Dragon Rage Staravia Running Shoes Masquerain Jolteon Pokemon Heroes Lugia.')
Post.create(body: 'Bulbasaur Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ivysaur Lorem ipsum')
Post.create(body: 'Pokem ipsum dolor sit amet Shiftry Vigoroth Suicune Venonat Vullaby Beldum. Lavender Town')
Post.create(body: 'Swablu Ghost Charizard Cleffa Tropius Keldeo. Mewtwo Strikes Back Super Potion Magikarp used')
Post.create(body: 'Splash Wailmer Deoxys Giovanni Sableye. Glitch City Seadra bicycle Larvitar Rainbow Badge')
Post.create(body: 'Druddigon Skarmory. Charizard Munchlax Vibrava Salamence Volcano Badge Rampardos')
Post.create(body: 'Quis nostrud exercitation ullamco laboris nisi Potion Magmar Druddigon')
Post.create(body: 'Zephyr Badge Palpitoad Bubble Snivy Omanyte')
Post.create(body: 'Mantine Krookodile. Sinnoh Hidden Machine gotta catch \'em all Hydreigon Cacnea Raticate Flygon')
Post.create(body: 'Dragon Rage Staravia Running Shoes Masquerain Jolteon Pokemon Heroes Lugia.')
Post.create(body: 'Bulbasaur Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ivysaur Lorem ipsum')
Post.create(body: 'Pokem ipsum dolor sit amet Shiftry Vigoroth Suicune Venonat Vullaby Beldum. Lavender Town')
Post.create(body: 'Swablu Ghost Charizard Cleffa Tropius Keldeo. Mewtwo Strikes Back Super Potion Magikarp used')
Post.create(body: 'Splash Wailmer Deoxys Giovanni Sableye. Glitch City Seadra bicycle Larvitar Rainbow Badge')
Post.create(body: 'Druddigon Skarmory. Charizard Munchlax Vibrava Salamence Volcano Badge Rampardos')
Post.create(body: 'Quis nostrud exercitation ullamco laboris nisi Potion Magmar Druddigon')
Post.create(body: 'Zephyr Badge Palpitoad Bubble Snivy Omanyte')
Post.create(body: 'Mantine Krookodile. Sinnoh Hidden Machine gotta catch \'em all Hydreigon Cacnea Raticate Flygon')
Post.create(body: 'Dragon Rage Staravia Running Shoes Masquerain Jolteon Pokemon Heroes Lugia.')
Post.create(body: 'Bulbasaur Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ivysaur Lorem ipsum')
Post.create(body: 'Pokem ipsum dolor sit amet Shiftry Vigoroth Suicune Venonat Vullaby Beldum. Lavender Town')
Post.create(body: 'Swablu Ghost Charizard Cleffa Tropius Keldeo. Mewtwo Strikes Back Super Potion Magikarp used')
Post.create(body: 'Splash Wailmer Deoxys Giovanni Sableye. Glitch City Seadra bicycle Larvitar Rainbow Badge')
Post.create(body: 'Druddigon Skarmory. Charizard Munchlax Vibrava Salamence Volcano Badge Rampardos')
Post.create(body: 'Quis nostrud exercitation ullamco laboris nisi Potion Magmar Druddigon')
Post.create(body: 'Zephyr Badge Palpitoad Bubble Snivy Omanyte')
Post.create(body: 'Mantine Krookodile. Sinnoh Hidden Machine gotta catch \'em all Hydreigon Cacnea Raticate Flygon')
Post.create(body: 'Dragon Rage Staravia Running Shoes Masquerain Jolteon Pokemon Heroes Lugia.')
Post.create(body: 'Bulbasaur Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ivysaur Lorem ipsum')
Post.create(body: 'Pokem ipsum dolor sit amet Shiftry Vigoroth Suicune Venonat Vullaby Beldum. Lavender Town')
Post.create(body: 'Swablu Ghost Charizard Cleffa Tropius Keldeo. Mewtwo Strikes Back Super Potion Magikarp used')
Post.create(body: 'Splash Wailmer Deoxys Giovanni Sableye. Glitch City Seadra bicycle Larvitar Rainbow Badge')
Post.create(body: 'Druddigon Skarmory. Charizard Munchlax Vibrava Salamence Volcano Badge Rampardos')
Post.create(body: 'Quis nostrud exercitation ullamco laboris nisi Potion Magmar Druddigon')
Post.create(body: 'Zephyr Badge Palpitoad Bubble Snivy Omanyte')
Post.create(body: 'Mantine Krookodile. Sinnoh Hidden Machine gotta catch \'em all Hydreigon Cacnea Raticate Flygon')
Post.create(body: 'Dragon Rage Staravia Running Shoes Masquerain Jolteon Pokemon Heroes Lugia.')
Post.create(body: 'Bulbasaur Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ivysaur Lorem ipsum')
Post.create(body: 'Pokem ipsum dolor sit amet Shiftry Vigoroth Suicune Venonat Vullaby Beldum. Lavender Town')
Post.create(body: 'Swablu Ghost Charizard Cleffa Tropius Keldeo. Mewtwo Strikes Back Super Potion Magikarp used')
Post.create(body: 'Splash Wailmer Deoxys Giovanni Sableye. Glitch City Seadra bicycle Larvitar Rainbow Badge')
Post.create(body: 'Druddigon Skarmory. Charizard Munchlax Vibrava Salamence Volcano Badge Rampardos')
Post.create(body: 'Quis nostrud exercitation ullamco laboris nisi Potion Magmar Druddigon')
Post.create(body: 'Zephyr Badge Palpitoad Bubble Snivy Omanyte')
Post.create(body: 'Mantine Krookodile. Sinnoh Hidden Machine gotta catch \'em all Hydreigon Cacnea Raticate Flygon')
Post.create(body: 'Dragon Rage Staravia Running Shoes Masquerain Jolteon Pokemon Heroes Lugia.')
Post.create(body: 'Bulbasaur Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ivysaur Lorem ipsum')
Post.create(body: 'Pokem ipsum dolor sit amet Shiftry Vigoroth Suicune Venonat Vullaby Beldum. Lavender Town')
Post.create(body: 'Swablu Ghost Charizard Cleffa Tropius Keldeo. Mewtwo Strikes Back Super Potion Magikarp used')
Post.create(body: 'Splash Wailmer Deoxys Giovanni Sableye. Glitch City Seadra bicycle Larvitar Rainbow Badge')
Post.create(body: 'Druddigon Skarmory. Charizard Munchlax Vibrava Salamence Volcano Badge Rampardos')
Post.create(body: 'Quis nostrud exercitation ullamco laboris nisi Potion Magmar Druddigon')
Post.create(body: 'Zephyr Badge Palpitoad Bubble Snivy Omanyte')
Post.create(body: 'Mantine Krookodile. Sinnoh Hidden Machine gotta catch \'em all Hydreigon Cacnea Raticate Flygon')
Post.create(body: 'Dragon Rage Staravia Running Shoes Masquerain Jolteon Pokemon Heroes Lugia.')
Post.create(body: 'Bulbasaur Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ivysaur Lorem ipsum')
Post.create(body: 'Pokem ipsum dolor sit amet Shiftry Vigoroth Suicune Venonat Vullaby Beldum. Lavender Town')
Post.create(body: 'Swablu Ghost Charizard Cleffa Tropius Keldeo. Mewtwo Strikes Back Super Potion Magikarp used')
Post.create(body: 'Splash Wailmer Deoxys Giovanni Sableye. Glitch City Seadra bicycle Larvitar Rainbow Badge')
Post.create(body: 'Druddigon Skarmory. Charizard Munchlax Vibrava Salamence Volcano Badge Rampardos')
Post.create(body: 'Quis nostrud exercitation ullamco laboris nisi Potion Magmar Druddigon')
Post.create(body: 'Zephyr Badge Palpitoad Bubble Snivy Omanyte')
Post.create(body: 'Mantine Krookodile. Sinnoh Hidden Machine gotta catch \'em all Hydreigon Cacnea Raticate Flygon')
Post.create(body: 'Dragon Rage Staravia Running Shoes Masquerain Jolteon Pokemon Heroes Lugia.')
Post.create(body: 'Bulbasaur Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ivysaur Lorem ipsum')
Post.create(body: 'Pokem ipsum dolor sit amet Shiftry Vigoroth Suicune Venonat Vullaby Beldum. Lavender Town')
Post.create(body: 'Swablu Ghost Charizard Cleffa Tropius Keldeo. Mewtwo Strikes Back Super Potion Magikarp used')
Post.create(body: 'Splash Wailmer Deoxys Giovanni Sableye. Glitch City Seadra bicycle Larvitar Rainbow Badge')
Post.create(body: 'Druddigon Skarmory. Charizard Munchlax Vibrava Salamence Volcano Badge Rampardos')
Post.create(body: 'Quis nostrud exercitation ullamco laboris nisi Potion Magmar Druddigon')
Post.create(body: 'Zephyr Badge Palpitoad Bubble Snivy Omanyte')
Post.create(body: 'Mantine Krookodile. Sinnoh Hidden Machine gotta catch \'em all Hydreigon Cacnea Raticate Flygon')
Post.create(body: 'Dragon Rage Staravia Running Shoes Masquerain Jolteon Pokemon Heroes Lugia.')
Post.create(body: 'Bulbasaur Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ivysaur Lorem ipsum')
Post.create(body: 'Pokem ipsum dolor sit amet Shiftry Vigoroth Suicune Venonat Vullaby Beldum. Lavender Town')
Post.create(body: 'Swablu Ghost Charizard Cleffa Tropius Keldeo. Mewtwo Strikes Back Super Potion Magikarp used')
Post.create(body: 'Splash Wailmer Deoxys Giovanni Sableye. Glitch City Seadra bicycle Larvitar Rainbow Badge')
Post.create(body: 'Druddigon Skarmory. Charizard Munchlax Vibrava Salamence Volcano Badge Rampardos')
Post.create(body: 'Quis nostrud exercitation ullamco laboris nisi Potion Magmar Druddigon')
Post.create(body: 'Zephyr Badge Palpitoad Bubble Snivy Omanyte')
Post.create(body: 'Mantine Krookodile. Sinnoh Hidden Machine gotta catch \'em all Hydreigon Cacnea Raticate Flygon')
Post.create(body: 'Dragon Rage Staravia Running Shoes Masquerain Jolteon Pokemon Heroes Lugia.')
Post.create(body: 'Bulbasaur Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ivysaur Lorem ipsum')
Post.create(body: 'Pokem ipsum dolor sit amet Shiftry Vigoroth Suicune Venonat Vullaby Beldum. Lavender Town')
Post.create(body: 'Swablu Ghost Charizard Cleffa Tropius Keldeo. Mewtwo Strikes Back Super Potion Magikarp used')
Post.create(body: 'Splash Wailmer Deoxys Giovanni Sableye. Glitch City Seadra bicycle Larvitar Rainbow Badge')
Post.create(body: 'Druddigon Skarmory. Charizard Munchlax Vibrava Salamence Volcano Badge Rampardos')
Post.create(body: 'Quis nostrud exercitation ullamco laboris nisi Potion Magmar Druddigon')
Post.create(body: 'Zephyr Badge Palpitoad Bubble Snivy Omanyte')
Post.create(body: 'Mantine Krookodile. Sinnoh Hidden Machine gotta catch \'em all Hydreigon Cacnea Raticate Flygon')
Post.create(body: 'Dragon Rage Staravia Running Shoes Masquerain Jolteon Pokemon Heroes Lugia.')
Post.create(body: 'Bulbasaur Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ivysaur Lorem ipsum')
Post.create(body: 'Pokem ipsum dolor sit amet Shiftry Vigoroth Suicune Venonat Vullaby Beldum. Lavender Town')
Post.create(body: 'Swablu Ghost Charizard Cleffa Tropius Keldeo. Mewtwo Strikes Back Super Potion Magikarp used')
Post.create(body: 'Splash Wailmer Deoxys Giovanni Sableye. Glitch City Seadra bicycle Larvitar Rainbow Badge')
Post.create(body: 'Druddigon Skarmory. Charizard Munchlax Vibrava Salamence Volcano Badge Rampardos')
Post.create(body: 'Quis nostrud exercitation ullamco laboris nisi Potion Magmar Druddigon')
Post.create(body: 'Zephyr Badge Palpitoad Bubble Snivy Omanyte')
Post.create(body: 'Mantine Krookodile. Sinnoh Hidden Machine gotta catch \'em all Hydreigon Cacnea Raticate Flygon')
Post.create(body: 'Dragon Rage Staravia Running Shoes Masquerain Jolteon Pokemon Heroes Lugia.')
Post.create(body: 'Bulbasaur Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ivysaur Lorem ipsum')
Post.create(body: 'Pokem ipsum dolor sit amet Shiftry Vigoroth Suicune Venonat Vullaby Beldum. Lavender Town')
Post.create(body: 'Swablu Ghost Charizard Cleffa Tropius Keldeo. Mewtwo Strikes Back Super Potion Magikarp used')
Post.create(body: 'Splash Wailmer Deoxys Giovanni Sableye. Glitch City Seadra bicycle Larvitar Rainbow Badge')
Post.create(body: 'Druddigon Skarmory. Charizard Munchlax Vibrava Salamence Volcano Badge Rampardos')
Post.create(body: 'Quis nostrud exercitation ullamco laboris nisi Potion Magmar Druddigon')
Post.create(body: 'Zephyr Badge Palpitoad Bubble Snivy Omanyte')
Post.create(body: 'Mantine Krookodile. Sinnoh Hidden Machine gotta catch \'em all Hydreigon Cacnea Raticate Flygon')
Post.create(body: 'Dragon Rage Staravia Running Shoes Masquerain Jolteon Pokemon Heroes Lugia.')
Post.create(body: 'Bulbasaur Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ivysaur Lorem ipsum')
Post.create(body: 'Pokem ipsum dolor sit amet Shiftry Vigoroth Suicune Venonat Vullaby Beldum. Lavender Town')
Post.create(body: 'Swablu Ghost Charizard Cleffa Tropius Keldeo. Mewtwo Strikes Back Super Potion Magikarp used')
Post.create(body: 'Splash Wailmer Deoxys Giovanni Sableye. Glitch City Seadra bicycle Larvitar Rainbow Badge')
Post.create(body: 'Druddigon Skarmory. Charizard Munchlax Vibrava Salamence Volcano Badge Rampardos')
Post.create(body: 'Quis nostrud exercitation ullamco laboris nisi Potion Magmar Druddigon')
Post.create(body: 'Zephyr Badge Palpitoad Bubble Snivy Omanyte')
Post.create(body: 'Mantine Krookodile. Sinnoh Hidden Machine gotta catch \'em all Hydreigon Cacnea Raticate Flygon')
Post.create(body: 'Dragon Rage Staravia Running Shoes Masquerain Jolteon Pokemon Heroes Lugia.')
Post.create(body: 'Bulbasaur Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ivysaur Lorem ipsum')
Post.create(body: 'Pokem ipsum dolor sit amet Shiftry Vigoroth Suicune Venonat Vullaby Beldum. Lavender Town')
Post.create(body: 'Swablu Ghost Charizard Cleffa Tropius Keldeo. Mewtwo Strikes Back Super Potion Magikarp used')
Post.create(body: 'Splash Wailmer Deoxys Giovanni Sableye. Glitch City Seadra bicycle Larvitar Rainbow Badge')
Post.create(body: 'Druddigon Skarmory. Charizard Munchlax Vibrava Salamence Volcano Badge Rampardos')
Post.create(body: 'Quis nostrud exercitation ullamco laboris nisi Potion Magmar Druddigon')
Post.create(body: 'Zephyr Badge Palpitoad Bubble Snivy Omanyte')
Post.create(body: 'Mantine Krookodile. Sinnoh Hidden Machine gotta catch \'em all Hydreigon Cacnea Raticate Flygon')
Post.create(body: 'Dragon Rage Staravia Running Shoes Masquerain Jolteon Pokemon Heroes Lugia.')
Post.create(body: 'Bulbasaur Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ivysaur Lorem ipsum')
Post.create(body: 'Pokem ipsum dolor sit amet Shiftry Vigoroth Suicune Venonat Vullaby Beldum. Lavender Town')
Post.create(body: 'Swablu Ghost Charizard Cleffa Tropius Keldeo. Mewtwo Strikes Back Super Potion Magikarp used')
Post.create(body: 'Splash Wailmer Deoxys Giovanni Sableye. Glitch City Seadra bicycle Larvitar Rainbow Badge')
Post.create(body: 'Druddigon Skarmory. Charizard Munchlax Vibrava Salamence Volcano Badge Rampardos')
Post.create(body: 'Quis nostrud exercitation ullamco laboris nisi Potion Magmar Druddigon')
Post.create(body: 'Zephyr Badge Palpitoad Bubble Snivy Omanyte')
Post.create(body: 'Mantine Krookodile. Sinnoh Hidden Machine gotta catch \'em all Hydreigon Cacnea Raticate Flygon')
Post.create(body: 'Dragon Rage Staravia Running Shoes Masquerain Jolteon Pokemon Heroes Lugia.')
Post.create(body: 'Bulbasaur Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ivysaur Lorem ipsum')
Post.create(body: 'Pokem ipsum dolor sit amet Shiftry Vigoroth Suicune Venonat Vullaby Beldum. Lavender Town')
Post.create(body: 'Swablu Ghost Charizard Cleffa Tropius Keldeo. Mewtwo Strikes Back Super Potion Magikarp used')
Post.create(body: 'Splash Wailmer Deoxys Giovanni Sableye. Glitch City Seadra bicycle Larvitar Rainbow Badge')
Post.create(body: 'Druddigon Skarmory. Charizard Munchlax Vibrava Salamence Volcano Badge Rampardos')
Post.create(body: 'Quis nostrud exercitation ullamco laboris nisi Potion Magmar Druddigon')
Post.create(body: 'Zephyr Badge Palpitoad Bubble Snivy Omanyte')
Post.create(body: 'Mantine Krookodile. Sinnoh Hidden Machine gotta catch \'em all Hydreigon Cacnea Raticate Flygon')
Post.create(body: 'Dragon Rage Staravia Running Shoes Masquerain Jolteon Pokemon Heroes Lugia.')
Post.create(body: 'Bulbasaur Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ivysaur Lorem ipsum')
Post.create(body: 'Pokem ipsum dolor sit amet Shiftry Vigoroth Suicune Venonat Vullaby Beldum. Lavender Town')
Post.create(body: 'Swablu Ghost Charizard Cleffa Tropius Keldeo. Mewtwo Strikes Back Super Potion Magikarp used')
Post.create(body: 'Splash Wailmer Deoxys Giovanni Sableye. Glitch City Seadra bicycle Larvitar Rainbow Badge')
Post.create(body: 'Druddigon Skarmory. Charizard Munchlax Vibrava Salamence Volcano Badge Rampardos')
Post.create(body: 'Quis nostrud exercitation ullamco laboris nisi Potion Magmar Druddigon')
Post.create(body: 'Zephyr Badge Palpitoad Bubble Snivy Omanyte')
Post.create(body: 'Mantine Krookodile. Sinnoh Hidden Machine gotta catch \'em all Hydreigon Cacnea Raticate Flygon')
Post.create(body: 'Dragon Rage Staravia Running Shoes Masquerain Jolteon Pokemon Heroes Lugia.')
Post.create(body: 'Bulbasaur Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ivysaur Lorem ipsum')
Post.create(body: 'Pokem ipsum dolor sit amet Shiftry Vigoroth Suicune Venonat Vullaby Beldum. Lavender Town')
Post.create(body: 'Swablu Ghost Charizard Cleffa Tropius Keldeo. Mewtwo Strikes Back Super Potion Magikarp used')
Post.create(body: 'Splash Wailmer Deoxys Giovanni Sableye. Glitch City Seadra bicycle Larvitar Rainbow Badge')
Post.create(body: 'Druddigon Skarmory. Charizard Munchlax Vibrava Salamence Volcano Badge Rampardos')
Post.create(body: 'Quis nostrud exercitation ullamco laboris nisi Potion Magmar Druddigon')
Post.create(body: 'Zephyr Badge Palpitoad Bubble Snivy Omanyte')
Post.create(body: 'Mantine Krookodile. Sinnoh Hidden Machine gotta catch \'em all Hydreigon Cacnea Raticate Flygon')
Post.create(body: 'Dragon Rage Staravia Running Shoes Masquerain Jolteon Pokemon Heroes Lugia.')
Post.create(body: 'Bulbasaur Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ivysaur Lorem ipsum')
Post.create(body: 'Pokem ipsum dolor sit amet Shiftry Vigoroth Suicune Venonat Vullaby Beldum. Lavender Town')
Post.create(body: 'Swablu Ghost Charizard Cleffa Tropius Keldeo. Mewtwo Strikes Back Super Potion Magikarp used')
Post.create(body: 'Splash Wailmer Deoxys Giovanni Sableye. Glitch City Seadra bicycle Larvitar Rainbow Badge')
Post.create(body: 'Druddigon Skarmory. Charizard Munchlax Vibrava Salamence Volcano Badge Rampardos')
Post.create(body: 'Quis nostrud exercitation ullamco laboris nisi Potion Magmar Druddigon')
Post.create(body: 'Zephyr Badge Palpitoad Bubble Snivy Omanyte')
Post.create(body: 'Mantine Krookodile. Sinnoh Hidden Machine gotta catch \'em all Hydreigon Cacnea Raticate Flygon')
Post.create(body: 'Dragon Rage Staravia Running Shoes Masquerain Jolteon Pokemon Heroes Lugia.')
